spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudvendor?useSSL=false
    username: root
    password: root

  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#JPA Settings
  jpa.hibernate.ddl_auto: create
